#!/usr/bin/env ruby

puts "Toggling Reith Proxies"

require 'pathname'
require "optparse"
require File.join(File.dirname(Pathname.new(__FILE__).realpath), *%w[/services.rb])

options = {:default => "args"}

def proxies_on
  puts "Putting proxies on"
  Services.toggle_all(:on)
end

def proxies_off
  puts "Putting proxies off"
  Services.toggle_all(:off)
end



ARGV.options do |opts|
  opts.banner = "Usage:  #{File.basename($PROGRAM_NAME)} [OPTIONS] on|off\n  Run as 'reithproxies off'"
  
  opts.separator ""
  opts.separator "Specific Options:"
  
  opts.on( "-n", "--on",
            "Turn proxies on" ) do
    puts "Turning on proxies"
    proxies_on
    exit
  end
  
  opts.on( "-f", "--off",
            "Turn proxies off" ) do
    puts "Turning off proxies"
    proxies_off
    exit
  end
  
  
  opts.separator "Common Options:"
  
  
  opts.on( "-h", "--help",
           "Show this message." ) do
    puts opts
    exit
  end
  
  opts.parse!
end
# finally, respond to on or off as the last argument
# ordinarily you won't get here
if ARGV.length > 0
  argv = ARGV.shift.downcase
  if argv == "on"
	puts "Turning on proxies"
    proxies_on
  end
  if argv == "off"
	puts "Turning off proxies"
    proxies_off
  end
end
puts "try 'reithproxies -h' for help"
